[package]
name = "game_3d"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.15"

# Enable optimizations for dependencies in dev builds for better performance
[profile.dev.package."*"]
opt-level = 3

# Enable link-time optimization for release builds
[profile.release]
lto = "thin"
